/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by bindgen.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Subject = IDL.Record({
  'id' : IDL.Nat,
  'weight' : IDL.Nat,
  'name' : IDL.Text,
});
export const TaskDifficulty = IDL.Variant({
  'Low' : IDL.Null,
  'High' : IDL.Null,
  'Medium' : IDL.Null,
});
export const TaskStatus = IDL.Variant({
  'Scheduled' : IDL.Null,
  'InProgress' : IDL.Null,
  'Completed' : IDL.Null,
});
export const TaskUnit = IDL.Record({
  'id' : IDL.Nat,
  'status' : TaskStatus,
  'title' : IDL.Text,
  'difficulty' : TaskDifficulty,
  'deadline' : IDL.Text,
  'subjectId' : IDL.Nat,
  'estimatedMinutes' : IDL.Nat,
});
export const User = IDL.Record({
  'id' : IDL.Nat,
  'fatigueLevel' : IDL.Nat,
  'maxDailyHours' : IDL.Nat,
  'name' : IDL.Text,
});
export const ProgressLog = IDL.Record({
  'completed' : IDL.Bool,
  'interruptions' : IDL.Nat,
  'taskId' : IDL.Nat,
  'actualTime' : IDL.Nat,
});
export const FocusSession = IDL.Record({
  'isBreak' : IDL.Bool,
  'taskId' : IDL.Nat,
  'sessionNumber' : IDL.Nat,
  'durationMinutes' : IDL.Nat,
});
export const SubjectPerformance = IDL.Record({
  'avgScore' : IDL.Nat,
  'completedTasks' : IDL.Nat,
  'subjectName' : IDL.Text,
});
export const WeeklyHours = IDL.Record({ 'day' : IDL.Text, 'hours' : IDL.Nat });
export const FocusScorePoint = IDL.Record({
  'date' : IDL.Text,
  'score' : IDL.Nat,
});
export const AnalyticsData = IDL.Record({
  'subjectPerformance' : IDL.Vec(SubjectPerformance),
  'weeklyHours' : IDL.Vec(WeeklyHours),
  'focusScoreHistory' : IDL.Vec(FocusScorePoint),
});
export const ScheduledBlock = IDL.Record({
  'subjectName' : IDL.Text,
  'difficulty' : TaskDifficulty,
  'taskTitle' : IDL.Text,
  'taskId' : IDL.Nat,
  'priorityScore' : IDL.Nat,
  'timeSlot' : IDL.Text,
  'estimatedMinutes' : IDL.Nat,
});
export const DashboardData = IDL.Record({
  'totalTasks' : IDL.Nat,
  'completedTasks' : IDL.Nat,
  'dailyProgress' : IDL.Nat,
  'focusScore' : IDL.Nat,
  'scheduledTasks' : IDL.Nat,
  'studyStreak' : IDL.Nat,
  'inProgressTasks' : IDL.Nat,
  'stabilityScore' : IDL.Nat,
});
export const PriorityQueueItem = IDL.Record({
  'subjectName' : IDL.Text,
  'difficulty' : TaskDifficulty,
  'taskTitle' : IDL.Text,
  'deadline' : IDL.Text,
  'taskId' : IDL.Nat,
  'priorityScore' : IDL.Nat,
});
export const SubjectLeaderboardEntry = IDL.Record({
  'totalTasks' : IDL.Nat,
  'completionRate' : IDL.Nat,
  'completedTasks' : IDL.Nat,
  'subjectName' : IDL.Text,
  'subjectId' : IDL.Nat,
});
export const TaskStats = IDL.Record({
  'inProgressCount' : IDL.Nat,
  'completedCount' : IDL.Nat,
  'scheduledCount' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addSubject' : IDL.Func([IDL.Text, IDL.Nat], [Subject], []),
  'addTask' : IDL.Func(
      [IDL.Nat, IDL.Text, TaskDifficulty, IDL.Nat, IDL.Text],
      [TaskUnit],
      [],
    ),
  'createUser' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [User], []),
  'deleteTask' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'endFocusSession' : IDL.Func([], [IDL.Opt(ProgressLog)], []),
  'getActiveSession' : IDL.Func([], [IDL.Opt(FocusSession)], ['query']),
  'getAnalytics' : IDL.Func([], [AnalyticsData], ['query']),
  'getDailySchedule' : IDL.Func([], [IDL.Vec(ScheduledBlock)], ['query']),
  'getDashboard' : IDL.Func([], [DashboardData], ['query']),
  'getPriorityQueue' : IDL.Func([], [IDL.Vec(PriorityQueueItem)], ['query']),
  'getSubjectLeaderboard' : IDL.Func(
      [],
      [IDL.Vec(SubjectLeaderboardEntry)],
      ['query'],
    ),
  'getTaskStats' : IDL.Func([], [TaskStats], ['query']),
  'getUser' : IDL.Func([], [IDL.Opt(User)], ['query']),
  'listSubjects' : IDL.Func([], [IDL.Vec(Subject)], ['query']),
  'listTasks' : IDL.Func([], [IDL.Vec(TaskUnit)], ['query']),
  'logProgress' : IDL.Func(
      [IDL.Nat, IDL.Bool, IDL.Nat, IDL.Nat],
      [ProgressLog],
      [],
    ),
  'recordInterruption' : IDL.Func([], [], []),
  'removeSubject' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'seedDemoData' : IDL.Func([], [], []),
  'startFocusSession' : IDL.Func([IDL.Nat], [FocusSession], []),
  'updateTaskStatus' : IDL.Func([IDL.Nat, TaskStatus], [IDL.Opt(TaskUnit)], []),
  'updateUser' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [User], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Subject = IDL.Record({
    'id' : IDL.Nat,
    'weight' : IDL.Nat,
    'name' : IDL.Text,
  });
  const TaskDifficulty = IDL.Variant({
    'Low' : IDL.Null,
    'High' : IDL.Null,
    'Medium' : IDL.Null,
  });
  const TaskStatus = IDL.Variant({
    'Scheduled' : IDL.Null,
    'InProgress' : IDL.Null,
    'Completed' : IDL.Null,
  });
  const TaskUnit = IDL.Record({
    'id' : IDL.Nat,
    'status' : TaskStatus,
    'title' : IDL.Text,
    'difficulty' : TaskDifficulty,
    'deadline' : IDL.Text,
    'subjectId' : IDL.Nat,
    'estimatedMinutes' : IDL.Nat,
  });
  const User = IDL.Record({
    'id' : IDL.Nat,
    'fatigueLevel' : IDL.Nat,
    'maxDailyHours' : IDL.Nat,
    'name' : IDL.Text,
  });
  const ProgressLog = IDL.Record({
    'completed' : IDL.Bool,
    'interruptions' : IDL.Nat,
    'taskId' : IDL.Nat,
    'actualTime' : IDL.Nat,
  });
  const FocusSession = IDL.Record({
    'isBreak' : IDL.Bool,
    'taskId' : IDL.Nat,
    'sessionNumber' : IDL.Nat,
    'durationMinutes' : IDL.Nat,
  });
  const SubjectPerformance = IDL.Record({
    'avgScore' : IDL.Nat,
    'completedTasks' : IDL.Nat,
    'subjectName' : IDL.Text,
  });
  const WeeklyHours = IDL.Record({ 'day' : IDL.Text, 'hours' : IDL.Nat });
  const FocusScorePoint = IDL.Record({ 'date' : IDL.Text, 'score' : IDL.Nat });
  const AnalyticsData = IDL.Record({
    'subjectPerformance' : IDL.Vec(SubjectPerformance),
    'weeklyHours' : IDL.Vec(WeeklyHours),
    'focusScoreHistory' : IDL.Vec(FocusScorePoint),
  });
  const ScheduledBlock = IDL.Record({
    'subjectName' : IDL.Text,
    'difficulty' : TaskDifficulty,
    'taskTitle' : IDL.Text,
    'taskId' : IDL.Nat,
    'priorityScore' : IDL.Nat,
    'timeSlot' : IDL.Text,
    'estimatedMinutes' : IDL.Nat,
  });
  const DashboardData = IDL.Record({
    'totalTasks' : IDL.Nat,
    'completedTasks' : IDL.Nat,
    'dailyProgress' : IDL.Nat,
    'focusScore' : IDL.Nat,
    'scheduledTasks' : IDL.Nat,
    'studyStreak' : IDL.Nat,
    'inProgressTasks' : IDL.Nat,
    'stabilityScore' : IDL.Nat,
  });
  const PriorityQueueItem = IDL.Record({
    'subjectName' : IDL.Text,
    'difficulty' : TaskDifficulty,
    'taskTitle' : IDL.Text,
    'deadline' : IDL.Text,
    'taskId' : IDL.Nat,
    'priorityScore' : IDL.Nat,
  });
  const SubjectLeaderboardEntry = IDL.Record({
    'totalTasks' : IDL.Nat,
    'completionRate' : IDL.Nat,
    'completedTasks' : IDL.Nat,
    'subjectName' : IDL.Text,
    'subjectId' : IDL.Nat,
  });
  const TaskStats = IDL.Record({
    'inProgressCount' : IDL.Nat,
    'completedCount' : IDL.Nat,
    'scheduledCount' : IDL.Nat,
  });
  
  return IDL.Service({
    'addSubject' : IDL.Func([IDL.Text, IDL.Nat], [Subject], []),
    'addTask' : IDL.Func(
        [IDL.Nat, IDL.Text, TaskDifficulty, IDL.Nat, IDL.Text],
        [TaskUnit],
        [],
      ),
    'createUser' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [User], []),
    'deleteTask' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'endFocusSession' : IDL.Func([], [IDL.Opt(ProgressLog)], []),
    'getActiveSession' : IDL.Func([], [IDL.Opt(FocusSession)], ['query']),
    'getAnalytics' : IDL.Func([], [AnalyticsData], ['query']),
    'getDailySchedule' : IDL.Func([], [IDL.Vec(ScheduledBlock)], ['query']),
    'getDashboard' : IDL.Func([], [DashboardData], ['query']),
    'getPriorityQueue' : IDL.Func([], [IDL.Vec(PriorityQueueItem)], ['query']),
    'getSubjectLeaderboard' : IDL.Func(
        [],
        [IDL.Vec(SubjectLeaderboardEntry)],
        ['query'],
      ),
    'getTaskStats' : IDL.Func([], [TaskStats], ['query']),
    'getUser' : IDL.Func([], [IDL.Opt(User)], ['query']),
    'listSubjects' : IDL.Func([], [IDL.Vec(Subject)], ['query']),
    'listTasks' : IDL.Func([], [IDL.Vec(TaskUnit)], ['query']),
    'logProgress' : IDL.Func(
        [IDL.Nat, IDL.Bool, IDL.Nat, IDL.Nat],
        [ProgressLog],
        [],
      ),
    'recordInterruption' : IDL.Func([], [], []),
    'removeSubject' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'seedDemoData' : IDL.Func([], [], []),
    'startFocusSession' : IDL.Func([IDL.Nat], [FocusSession], []),
    'updateTaskStatus' : IDL.Func(
        [IDL.Nat, TaskStatus],
        [IDL.Opt(TaskUnit)],
        [],
      ),
    'updateUser' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [User], []),
  });
};

export const init = ({ IDL }) => { return []; };