package com.studyflow.model;

/**
 * BreakBlock — a scheduled break slot between study sessions.
 * Generated by SchedulingService when interleaving breaks with study blocks.
 */
public class BreakBlock {

    private String timeSlot;
    private int durationMinutes;
    private String type; // "short" (5 min) | "long" (15 min)

    public BreakBlock() {}

    public BreakBlock(String timeSlot, int durationMinutes, String type) {
        this.timeSlot = timeSlot;
        this.durationMinutes = durationMinutes;
        this.type = type;
    }

    public String getTimeSlot() { return timeSlot; }
    public void setTimeSlot(String timeSlot) { this.timeSlot = timeSlot; }
    public int getDurationMinutes() { return durationMinutes; }
    public void setDurationMinutes(int durationMinutes) { this.durationMinutes = durationMinutes; }
    public String getType() { return type; }
    public void setType(String type) { this.type = type; }
}
