/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by bindgen.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface FocusScorePoint {
    date: string;
    score: bigint;
}
export interface SubjectLeaderboardEntry {
    totalTasks: bigint;
    completionRate: bigint;
    completedTasks: bigint;
    subjectName: string;
    subjectId: bigint;
}
export interface DashboardData {
    totalTasks: bigint;
    completedTasks: bigint;
    dailyProgress: bigint;
    focusScore: bigint;
    scheduledTasks: bigint;
    studyStreak: bigint;
    inProgressTasks: bigint;
    stabilityScore: bigint;
}
export interface User {
    id: bigint;
    fatigueLevel: bigint;
    maxDailyHours: bigint;
    name: string;
}
export interface TaskUnit {
    id: bigint;
    status: TaskStatus;
    title: string;
    difficulty: TaskDifficulty;
    deadline: string;
    subjectId: bigint;
    estimatedMinutes: bigint;
}
export interface PriorityQueueItem {
    subjectName: string;
    difficulty: TaskDifficulty;
    taskTitle: string;
    deadline: string;
    taskId: bigint;
    priorityScore: bigint;
}
export interface FocusSession {
    isBreak: boolean;
    taskId: bigint;
    sessionNumber: bigint;
    durationMinutes: bigint;
}
export interface TaskStats {
    inProgressCount: bigint;
    completedCount: bigint;
    scheduledCount: bigint;
}
export interface SubjectPerformance {
    avgScore: bigint;
    completedTasks: bigint;
    subjectName: string;
}
export interface ProgressLog {
    completed: boolean;
    interruptions: bigint;
    taskId: bigint;
    actualTime: bigint;
}
export interface ScheduledBlock {
    subjectName: string;
    difficulty: TaskDifficulty;
    taskTitle: string;
    taskId: bigint;
    priorityScore: bigint;
    timeSlot: string;
    estimatedMinutes: bigint;
}
export interface WeeklyHours {
    day: string;
    hours: bigint;
}
export interface Subject {
    id: bigint;
    weight: bigint;
    name: string;
}
export interface AnalyticsData {
    subjectPerformance: Array<SubjectPerformance>;
    weeklyHours: Array<WeeklyHours>;
    focusScoreHistory: Array<FocusScorePoint>;
}
export enum TaskDifficulty {
    Low = "Low",
    High = "High",
    Medium = "Medium"
}
export enum TaskStatus {
    Scheduled = "Scheduled",
    InProgress = "InProgress",
    Completed = "Completed"
}
export interface backendInterface {
    addSubject(name: string, weight: bigint): Promise<Subject>;
    addTask(subjectId: bigint, title: string, difficulty: TaskDifficulty, estimatedMinutes: bigint, deadline: string): Promise<TaskUnit>;
    createUser(name: string, maxDailyHours: bigint, fatigueLevel: bigint): Promise<User>;
    deleteTask(taskId: bigint): Promise<boolean>;
    endFocusSession(): Promise<ProgressLog | null>;
    getActiveSession(): Promise<FocusSession | null>;
    getAnalytics(): Promise<AnalyticsData>;
    getDailySchedule(): Promise<Array<ScheduledBlock>>;
    getDashboard(): Promise<DashboardData>;
    getPriorityQueue(): Promise<Array<PriorityQueueItem>>;
    getSubjectLeaderboard(): Promise<Array<SubjectLeaderboardEntry>>;
    getTaskStats(): Promise<TaskStats>;
    getUser(): Promise<User | null>;
    listSubjects(): Promise<Array<Subject>>;
    listTasks(): Promise<Array<TaskUnit>>;
    logProgress(taskId: bigint, completed: boolean, actualTime: bigint, interruptions: bigint): Promise<ProgressLog>;
    recordInterruption(): Promise<void>;
    removeSubject(id: bigint): Promise<boolean>;
    seedDemoData(): Promise<void>;
    startFocusSession(taskId: bigint): Promise<FocusSession>;
    updateTaskStatus(taskId: bigint, status: TaskStatus): Promise<TaskUnit | null>;
    updateUser(name: string, maxDailyHours: bigint, fatigueLevel: bigint): Promise<User>;
}
import type { FocusSession as _FocusSession, PriorityQueueItem as _PriorityQueueItem, ProgressLog as _ProgressLog, ScheduledBlock as _ScheduledBlock, TaskDifficulty as _TaskDifficulty, TaskStatus as _TaskStatus, TaskUnit as _TaskUnit, User as _User } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addSubject(arg0: string, arg1: bigint): Promise<Subject> {
        if (this.processError) {
            try {
                const result = await this.actor.addSubject(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSubject(arg0, arg1);
            return result;
        }
    }
    async addTask(arg0: bigint, arg1: string, arg2: TaskDifficulty, arg3: bigint, arg4: string): Promise<TaskUnit> {
        if (this.processError) {
            try {
                const result = await this.actor.addTask(arg0, arg1, to_candid_TaskDifficulty_n1(this._uploadFile, this._downloadFile, arg2), arg3, arg4);
                return from_candid_TaskUnit_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTask(arg0, arg1, to_candid_TaskDifficulty_n1(this._uploadFile, this._downloadFile, arg2), arg3, arg4);
            return from_candid_TaskUnit_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async createUser(arg0: string, arg1: bigint, arg2: bigint): Promise<User> {
        if (this.processError) {
            try {
                const result = await this.actor.createUser(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createUser(arg0, arg1, arg2);
            return result;
        }
    }
    async deleteTask(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTask(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTask(arg0);
            return result;
        }
    }
    async endFocusSession(): Promise<ProgressLog | null> {
        if (this.processError) {
            try {
                const result = await this.actor.endFocusSession();
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.endFocusSession();
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getActiveSession(): Promise<FocusSession | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveSession();
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveSession();
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAnalytics(): Promise<AnalyticsData> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnalytics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnalytics();
            return result;
        }
    }
    async getDailySchedule(): Promise<Array<ScheduledBlock>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailySchedule();
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailySchedule();
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboard(): Promise<DashboardData> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboard();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboard();
            return result;
        }
    }
    async getPriorityQueue(): Promise<Array<PriorityQueueItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPriorityQueue();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPriorityQueue();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSubjectLeaderboard(): Promise<Array<SubjectLeaderboardEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubjectLeaderboard();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubjectLeaderboard();
            return result;
        }
    }
    async getTaskStats(): Promise<TaskStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getTaskStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTaskStats();
            return result;
        }
    }
    async getUser(): Promise<User | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUser();
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUser();
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async listSubjects(): Promise<Array<Subject>> {
        if (this.processError) {
            try {
                const result = await this.actor.listSubjects();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listSubjects();
            return result;
        }
    }
    async listTasks(): Promise<Array<TaskUnit>> {
        if (this.processError) {
            try {
                const result = await this.actor.listTasks();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listTasks();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async logProgress(arg0: bigint, arg1: boolean, arg2: bigint, arg3: bigint): Promise<ProgressLog> {
        if (this.processError) {
            try {
                const result = await this.actor.logProgress(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logProgress(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async recordInterruption(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordInterruption();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordInterruption();
            return result;
        }
    }
    async removeSubject(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.removeSubject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeSubject(arg0);
            return result;
        }
    }
    async seedDemoData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.seedDemoData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedDemoData();
            return result;
        }
    }
    async startFocusSession(arg0: bigint): Promise<FocusSession> {
        if (this.processError) {
            try {
                const result = await this.actor.startFocusSession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startFocusSession(arg0);
            return result;
        }
    }
    async updateTaskStatus(arg0: bigint, arg1: TaskStatus): Promise<TaskUnit | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTaskStatus(arg0, to_candid_TaskStatus_n19(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTaskStatus(arg0, to_candid_TaskStatus_n19(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateUser(arg0: string, arg1: bigint, arg2: bigint): Promise<User> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUser(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUser(arg0, arg1, arg2);
            return result;
        }
    }
}
function from_candid_PriorityQueueItem_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PriorityQueueItem): PriorityQueueItem {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_ScheduledBlock_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ScheduledBlock): ScheduledBlock {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_TaskDifficulty_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TaskDifficulty): TaskDifficulty {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_TaskStatus_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TaskStatus): TaskStatus {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_TaskUnit_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TaskUnit): TaskUnit {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FocusSession]): FocusSession | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_User]): User | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TaskUnit]): TaskUnit | null {
    return value.length === 0 ? null : from_candid_TaskUnit_n3(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ProgressLog]): ProgressLog | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    subjectName: string;
    difficulty: _TaskDifficulty;
    taskTitle: string;
    taskId: bigint;
    priorityScore: bigint;
    timeSlot: string;
    estimatedMinutes: bigint;
}): {
    subjectName: string;
    difficulty: TaskDifficulty;
    taskTitle: string;
    taskId: bigint;
    priorityScore: bigint;
    timeSlot: string;
    estimatedMinutes: bigint;
} {
    return {
        subjectName: value.subjectName,
        difficulty: from_candid_TaskDifficulty_n7(_uploadFile, _downloadFile, value.difficulty),
        taskTitle: value.taskTitle,
        taskId: value.taskId,
        priorityScore: value.priorityScore,
        timeSlot: value.timeSlot,
        estimatedMinutes: value.estimatedMinutes
    };
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    subjectName: string;
    difficulty: _TaskDifficulty;
    taskTitle: string;
    deadline: string;
    taskId: bigint;
    priorityScore: bigint;
}): {
    subjectName: string;
    difficulty: TaskDifficulty;
    taskTitle: string;
    deadline: string;
    taskId: bigint;
    priorityScore: bigint;
} {
    return {
        subjectName: value.subjectName,
        difficulty: from_candid_TaskDifficulty_n7(_uploadFile, _downloadFile, value.difficulty),
        taskTitle: value.taskTitle,
        deadline: value.deadline,
        taskId: value.taskId,
        priorityScore: value.priorityScore
    };
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _TaskStatus;
    title: string;
    difficulty: _TaskDifficulty;
    deadline: string;
    subjectId: bigint;
    estimatedMinutes: bigint;
}): {
    id: bigint;
    status: TaskStatus;
    title: string;
    difficulty: TaskDifficulty;
    deadline: string;
    subjectId: bigint;
    estimatedMinutes: bigint;
} {
    return {
        id: value.id,
        status: from_candid_TaskStatus_n5(_uploadFile, _downloadFile, value.status),
        title: value.title,
        difficulty: from_candid_TaskDifficulty_n7(_uploadFile, _downloadFile, value.difficulty),
        deadline: value.deadline,
        subjectId: value.subjectId,
        estimatedMinutes: value.estimatedMinutes
    };
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Scheduled: null;
} | {
    InProgress: null;
} | {
    Completed: null;
}): TaskStatus {
    return "Scheduled" in value ? TaskStatus.Scheduled : "InProgress" in value ? TaskStatus.InProgress : "Completed" in value ? TaskStatus.Completed : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Low: null;
} | {
    High: null;
} | {
    Medium: null;
}): TaskDifficulty {
    return "Low" in value ? TaskDifficulty.Low : "High" in value ? TaskDifficulty.High : "Medium" in value ? TaskDifficulty.Medium : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ScheduledBlock>): Array<ScheduledBlock> {
    return value.map((x)=>from_candid_ScheduledBlock_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PriorityQueueItem>): Array<PriorityQueueItem> {
    return value.map((x)=>from_candid_PriorityQueueItem_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TaskUnit>): Array<TaskUnit> {
    return value.map((x)=>from_candid_TaskUnit_n3(_uploadFile, _downloadFile, x));
}
function to_candid_TaskDifficulty_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskDifficulty): _TaskDifficulty {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_TaskStatus_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskStatus): _TaskStatus {
    return to_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskDifficulty): {
    Low: null;
} | {
    High: null;
} | {
    Medium: null;
} {
    return value == TaskDifficulty.Low ? {
        Low: null
    } : value == TaskDifficulty.High ? {
        High: null
    } : value == TaskDifficulty.Medium ? {
        Medium: null
    } : value;
}
function to_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskStatus): {
    Scheduled: null;
} | {
    InProgress: null;
} | {
    Completed: null;
} {
    return value == TaskStatus.Scheduled ? {
        Scheduled: null
    } : value == TaskStatus.InProgress ? {
        InProgress: null
    } : value == TaskStatus.Completed ? {
        Completed: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
